import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
	title: "Next JS - About us",
	description: "Generated by create next app",
};

const page: React.FC = () => {
	return (
		<div>
			<h1>About us page</h1>
		</div>
	);
};

export default page;
