import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/components/AuthProvider";
import AuthComponent from "@/components/AuthComponent";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Next JS",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<AuthProvider>
				<body
					className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				>
					<header className="w-full border-b bg-white py-4 shadow-sm">
						<div className="mx-auto flex max-w-5xl items-center justify-between px-4">
							<h1 className="text-xl font-semibold">My App</h1>
							<nav className="flex gap-10 items-center">
								<a
									href="/"
									className="text-gray-600 hover:text-black"
								>
									Home
								</a>
								<a
									href="/about"
									className="text-gray-600 hover:text-black"
								>
									About
								</a>
								<a
									href="/blog"
									className="text-gray-600 hover:text-black"
								>
									Blog
								</a>
								<a
									href="/contact"
									className="text-gray-600 hover:text-black"
								>
									Contact
								</a>
								<a
									href="/profile"
									className="text-gray-600 hover:text-black"
								>
									Profile
								</a>
							</nav>
							<AuthComponent />
						</div>
					</header>

					<main className="min-h-screen w-full px-4 py-6 mx-auto max-w-5xl">
						{children}
					</main>

					<footer className="w-full border-t bg-gray-50 py-4 mt-10">
						<div className="mx-auto max-w-5xl px-4 text-center text-sm text-gray-600">
							© 2025 My App. All rights reserved.
						</div>
					</footer>
				</body>
			</AuthProvider>
		</html>
	);
}
