import Actions from "@/components/Actions";
import { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
	title: "Next JS - Home",
	description: "Generated by create next app",
};

export default function Home() {
	return (
		<div>
			<center>
				<h1 className="text-white text-6xl">Hello world</h1>
			</center>
			<center>
				{/* client component */}
				<Actions />
			</center>
		</div>
	);
}
