import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
	title: "Next JS - About us",
	description: "Generated by create next app",
};

const page: React.FC = () => {
	return (
		<div>
			<h1>Title </h1>
			<p>
				Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum
				quisquam explicabo perferendis nulla dolorem aliquid sit cum,
				tenetur harum provident recusandae totam hic. Accusantium,
				provident unde? Minus reprehenderit magni quas. Lorem ipsum
				dolor sit amet consectetur adipisicing elit. Nostrum quisquam
				explicabo perferendis nulla dolorem aliquid sit cum, tenetur
				harum provident recusandae totam hic. Accusantium, provident
				unde? Minus reprehenderit magni quas. Lorem ipsum dolor sit amet
				consectetur adipisicing elit. Nostrum quisquam explicabo
				perferendis nulla dolorem aliquid sit cum, tenetur harum
				provident recusandae totam hic. Accusantium, provident unde?
				Minus reprehenderit magni quas. Lorem ipsum dolor sit amet
				consectetur adipisicing elit. Nostrum quisquam explicabo
				perferendis nulla dolorem aliquid sit cum, tenetur harum
				provident recusandae totam hic. Accusantium, provident unde?
				Minus reprehenderit magni quas. Lorem ipsum dolor sit amet
				consectetur adipisicing elit. Nostrum quisquam explicabo
				perferendis nulla dolorem aliquid sit cum, tenetur harum
				provident recusandae totam hic. Accusantium, provident unde?
				Minus reprehenderit magni quas. Lorem ipsum dolor sit amet
				consectetur adipisicing elit. Nostrum quisquam explicabo
				perferendis nulla dolorem aliquid sit cum, tenetur harum
				provident recusandae totam hic. Accusantium, provident unde?
				Minus reprehenderit magni quas. Lorem ipsum dolor sit amet
				consectetur adipisicing elit. Nostrum quisquam explicabo
				perferendis nulla dolorem aliquid sit cum, tenetur harum
				provident recusandae totam hic. Accusantium, provident unde?
				Minus reprehenderit magni quas. Lorem ipsum dolor sit amet
				consectetur adipisicing elit. Nostrum quisquam explicabo
				perferendis nulla dolorem aliquid sit cum, tenetur harum
				provident recusandae totam hic. Accusantium, provident unde?
				Minus reprehenderit magni quas. Lorem ipsum dolor sit amet
				consectetur adipisicing elit. Nostrum quisquam explicabo
				perferendis nulla dolorem aliquid sit cum, tenetur harum
				provident recusandae totam hic. Accusantium, provident unde?
				Minus reprehenderit magni quas.
			</p>
		</div>
	);
};

export default page;
